### ISSUE TITLE
Add tags to icons for easier finding

### ISSUE THREAD

**Issue by FriederikeHanssen** [duerrsimon/bioicons#76] opened 2023-11-02 09:40 UTC
If I understand correctly, the current search is done by filename. It would be great if we could additionally add tags to each icon to make them easier to find, i.e. give a bunch of file icons the tag "file", even if the individual one might be named by the soecific file type it represents.

**Comment by duerrsimon** [comment] 2023-11-02 10:47
Closing this since it is a duplicate of #73 

This requires some changes to how the site renders the icons and I currently don't have the time to implement this. Happy to mentor someone in implementing this but ideally this feature is part of some more major changes to the architecture of the site.

**Closed by duerrsimon** 2023-11-02 10:47 UTC
